server:
  port: 8085
#   password:  oewfahkd3443f
#username: oesjfadknadf
spring:
  datasource:
    password: root
    url: jdbc:postgresql://32.134.345:5432/postgres
    username: postgres
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: never

app:
  maxSendMessageCount: 10
  maxSendMessageDuration: 3600000
jwt:
  accessToken:
    expirationInMls: 604800000
  refreshToken:
    expirationInMls: 1728000000
  secretKey: MaxfiySoz
orderLifeTime: 300000
paymeMinSumm: 5000
