server:
    port: 8085
spring:
    datasource:
        password: root
        url: jdbc:postgresql://localhost:5432/ticket
        username: postgres
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
                format_sql: true
        show-sql: true
    sql:
        init:
            mode: never
springdoc:
    api-docs:
        path: /api/swagger/docs
    swagger-ui:
        path: /api/swagger/swagger.html
twilio:
    accountSID: AC12f709df4c3da648649a6343133dfa85
    authToken: 060c08a5a7e9f3e0bb47e53361552227
    trialNumber: 19404129516

app:
    maxSendMessageCount: 10
    maxSendMessageDuration: 3600000
jwt:
    accessToken:
        expirationInMls: 604800000
    refreshToken:
        expirationInMls: 1728000000
    secretKey: MaxfiySoz
orderLifeTime: 600000
paymeMinSumm: 50
